### ISSUE TITLE
#TK21 Funcionalidad formulario de "crear evento"

### ISSUE THREAD

**Issue by Camigenti** [matiasp23/proyecto-fullstack-ispc-2022.github.io#60]

**Comment by planetageorgi** [comment]
NOTA: Crear tres botones: uno para publicar el evento que guarde la informacion completada y sea enviada a revision para los administradores. El segundo boton que permita editarla y tambien sea enviada a revision. El tercer botón para cancelar el evento en caso de requerirlo.
